In [9]:
import csv

2 March 2023

# **CSV Files**
---

We can open a text file also in csv format.<br/>
We should `import csv` before using it.<br/>
```python
csv.reader("Filename",delimiter=',')
```
Delimiter is the symbol which is used to separate each type of data

In [10]:
with open("text.txt") as csvfile:
    csv_reader=csv.reader(csvfile,delimiter=',')
    details=[]
    for i in csv_reader:
        details+=[i]
    details=details[1:]


In [11]:
with open("text.txt") as csv_file:
    csv_reader=csv.reader(csv_file)
    x=[]
    y=[]
    line_count=0
    for row in csv_reader:
        if line_count==0:
            print()
        else:
            x+=row[0]
            y+=row[1]
        line_count+=1
print(x,y)


['0', '1', '2', '3', '4'] ['0', '1', '2', '3', '4']


---
## **NumPy**
- Numberical Python
- Arrays (similar to list but around 50 times faster)
- Contiguous memory location("C" concept of arrays)
- Access and manipulate easier
- Written in C/C++
- ndarray object
- import numpy as np

- Create arrays of any dimension
- Array indexing/slicing
- Array reshaping
- Arange linespace functions
- Operation on array

In [42]:
import numpy as np
print(np.__version__,"\n")

arr=np.array([1,2,3,4,5])
#This is a 1-D array
print(id(arr))
print(id(arr[0]))
print(id(arr[1]))

print()
print(arr,"\n")
print(arr.itemsize, arr.strides)

arr2=np.array([[1,2,3,4,5],[5,6,7,8,8]])
print(arr2.itemsize,arr2.strides,'\n')
# This is like bitwise operation. First level of array is of elements
# which are arrays of size 5 ie 5*8=40 bytes.capitalize
# In the 2nd level, it is a list of 5 elements, each of which is an integer
# Thus 2nd level, the size of element is 8. This is what is done in stride.

d=np.array([[[1,2],[2,3]],[[1,2],[2,3]],[[1,2],[2,3]]])
print(d.ndim,d.shape, d.size, d.itemsize, d.strides, d.data,sep=' , ',end='\n\n')

e=np.arange(15) # We have numbers from 0 to 15
e=e.reshape(3,5) #Reshapes into 3 rows and 5 columns
print(e)

#We can now do indexing also in this. Everything is applicable, just that it is a numpy array


1.24.2 

4383220784
4658504304
4658504304

[1 2 3 4 5] 

8 (8,)
8 (40, 8) 

3 , (3, 2, 2) , 12 , 8 , (32, 16, 8) , <memory at 0x115b1c7c0>

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


We use something called `nd array` which is `n-dimensional` array.

In [43]:
zeroes = np.zeros((3,5))
ones = np.ones((3,5))
# Initiates an array with dimensions (3,5) and initiates with zeroes or ones

In [45]:
print(ones)
print(zeroes)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [51]:
linsp=np.linspace(0,5,10)
ar=np.arange(0,5.1,0.5)
# We get values from 0 to 10 and linearly space it into 10 values unlike arange which is basically just range
print(linsp)
print(ar)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
